# Generated by Django 3.0.3 on 2020-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('sender', models.CharField(max_length=100, verbose_name='발신자')),
                ('content', models.TextField(verbose_name='편지내용')),
            ],
        ),
    ]
